### ISSUE TITLE
Develop cross-bridge transition rate validation

### ISSUE THREAD

**Issue by dcolli23** [Campbell-Muscle-Lab/FiberSim#18]
# Description

We need to write some tests for cross-bridge transition rate validation.

**Comment by Sarah-Kst** [comment]
@kenatcampbellmusclelab  Updating this issue because I ran into something wrong. A super-relaxed dimer transitioned to a pair of detached/attached dimer, which is not supposed to happen in only one time step. 

![dimer_kinetics](https://user-images.githubusercontent.com/65904084/117842514-01a85600-b24c-11eb-9931-d28830a18736.PNG)

It is a simple three-state model (SRX-DRX-FG). I am gonna investigate if this is related to the SRX dimer kinetics or this can happen independently of the state type.

**Comment by Sarah-Kst** [comment]
Update: the problem was solved by adding a flag that is re-initialized each time a myosin head is even.

Ken suggested to change the loop over all the cb by a double loop (over the hubs then over the dimers) with a "continue" statement if a SRX transition is involved with the dimer. 

Sarah will update the code to implement this cleaner solution.

**Comment by Sarah-Kst** [comment]
Moving this issue to #89
